name: 01-workflow

on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: echo " hello world"
    echo-bye:
        runs-on: ubuntu-latest
        steps:
            - name: say bye
              run: |
                echo " hello bye"
                exit 1
            - name: checking
              run : echo " its working "
    echo-test:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: echo " test"