name: 03- runners

on: workflow_dispatch

jobs: 
    ubuntu-runner:
        runs-on: ubuntu-latest
        steps:
            - name: displaying the os
              run: |
               echo "hello"
               echo "$RUNNER_OS"

    Window-runner:
        runs-on: windows-latest
        steps:
            - name: displaying the os
              shell: bash
              run: |
               echo "hello"
               echo "$RUNNER_OS"
               ubuntu-runner:
    macos-runner:
        runs-on: MACOS-latest
        steps:
            - name: displaying the os
              run: |
               echo "hello"
               echo "$RUNNER_OS"

