name: 07 - Using Expressions
run-name: 07 - Using Expressions | DEBUG - ${{inputs.debug && 'on' || 'off'}} 
on: 
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] Print start-up data'
              if: ${{inputs.debug}}
              run: |
               echo "sucess"
               echo "print the ref ${{github.ref}}"

            - name: '[debug] Print when triggered from main'
              if: ${{inputs.debug && github.ref == 'refs/heads/main'}}
              run: echo "i triggered from main"

