name: 11 - Working with Inputs
on:
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                description: "Skip deployment and only print build output"
                default: false
            target:
                type: environment
                required: true
            tag:
              type: choice
              options:
                - v1
                - v2
                - v3

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Build
            run: echo "Building from tag ${{inputs.tag}}"
    deploy:
        runs-on: ubuntu-latest
        if: ${{!Inputs.dry-run}}
        needs:
            - build
        steps:
          - name: Build
            run: echo "Building from tag ${{inputs.target}}"
