name: 12 - Working with Outputs
on:
    workflow_dispatch:
        inputs:
          build-status:
            type: choice
            options:
                - success
                - failure
            default: success
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{steps.builds.outputs.status}}
        steps:
          - name: Print GITHUB_OUTPUT path
            run: echo "${{GITHUB.OUTPUT}}"
          - name: Build
            id: builds
            run: echo "status=${{inputs.build-status}}" >> "$GITHUB.OUTPUT"
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{!needs.build.outputs.build-status == 'success'}}
        steps:
            - name: Deploy 
              run: echo "Deployying "
